Code:You CAPSTONE PROJECT: Survivor Analysis

In [32]:
import pandas as pd 
import sqlite3

In [ ]:
# read in data

# Do I need Season Summary? Should I remove boot order since the is in Castaways?

df_castaway_details = pd.read_excel('survivoR.xlsx', sheet_name="Castaway Details")
df_castaways = pd.read_excel('survivoR.xlsx', sheet_name="Castaways")
df_advantage_details = pd.read_excel('survivoR.xlsx', sheet_name="Advantage Details")
df_advantage_movement = pd.read_excel('survivoR.xlsx', sheet_name="Advantage Movement")

# Data Wrangling

## Clean Castaway Details

In [41]:
# Castaway Details info

df_castaway_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1160 entries, 0 to 1159
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Castaway Id         1160 non-null   object
 1   Full Name           1158 non-null   object
 2   Full Name Detailed  1158 non-null   object
 3   Castaway            1160 non-null   object
 4   Last Name           1158 non-null   object
 5   Date of Birth       881 non-null    datetime64[ns]
 6   Date of Death       17 non-null     datetime64[ns]
 7   Gender              1160 non-null   object
 8   African             733 non-null    float64
 9   Asian               733 non-null    float64
 10  Latin American      733 non-null    float64
 11  Native American     733 non-null    float64
 12  Bipoc               733 non-null    float64
 13  Lgbt                1158 non-null   float64
 14  Personality Type    747 non-null    object
 15  Occupation          1158 non-null   object
 16  Collar              1136 non-null   object
 17  Three Words         418 non-null    object
 18  Hobbies             419 non-null    object
 19  Pet Peeves          390 non-null    object
 20  Race                175 non-null    object
 21  Ethnicity           114 non-null    object
dtypes: datetime64[ns](2), float64(6), object(14)
memory usage: 199.5+ KB

In [42]:
# drop columns from Castaway Details that aren't needed

df_castaway_details.drop(columns=['Full Name Detailed', 'Date of Death', 'Occupation', 'Collar', 'Three Words', 'Hobbies', 'Pet Peeves', 'Race', 'Ethnicity'])

,Castaway Id,Full Name,Castaway,Last Name,Date of Birth,Gender,African,Asian,Latin American,Native American,Bipoc,Lgbt,Personality Type
0,US0001,Sonja Christopher,Sonja,Christopher,1937-01-28,Female,0.0,0.0,0.0,0.0,0.0,1.0,ENFP
1,US0002,B.B. Andersen,B.B.,Andersen,1936-01-18,Male,0.0,0.0,0.0,0.0,0.0,0.0,ESTJ
2,US0003,Stacey Stillman,Stacey,Stillman,1972-08-11,Female,0.0,0.0,0.0,0.0,0.0,0.0,ENTJ
3,US0004,Ramona Gray,Ramona,Gray,1971-01-20,Female,1.0,0.0,0.0,0.0,1.0,0.0,ISTJ
4,US0005,Dirk Been,Dirk,Been,1976-06-15,Male,0.0,0.0,0.0,0.0,0.0,0.0,ISFP
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1155,NZ0030,Adam O'Brien,Adam,O'Brien,NaT,Male,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1156,NZ0031,Tara Thorowgood,Tara,Thorowgood,NaT,Female,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1157,NZ0032,Dave Lipanovic,Dave,Lipanovic,NaT,Male,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1158,NZ0033,Tess Fahey,Tess,Fahey,NaT,Female,NaN,NaN,NaN,NaN,NaN,0.0,NaN
1159,NZ0034,Lisa Stanger,Lisa,Stanger,NaT,Female,NaN,NaN,NaN,NaN,NaN,0.0,NaN

## Clean Castaways

In [43]:
# Castaways info

df_castaways.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1403 entries, 0 to 1402
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Version         1403 non-null   object
 1   Version Season  1403 non-null   object
 2   Season          1403 non-null   int64
 3   Full Name       1403 non-null   object
 4   Castaway Id     1403 non-null   object
 5   Castaway        1403 non-null   object
 6   Age             1361 non-null   float64
 7   City            1349 non-null   object
 8   State           1299 non-null   object
 9   Episode         1361 non-null   float64
 10  Day             1361 non-null   float64
 11  Order           1361 non-null   float64
 12  Result          1361 non-null   object
 13  Jury Status     601 non-null    object
 14  Place           1403 non-null   int64
 15  Original Tribe  1359 non-null   object
 16  Jury            1403 non-null   bool
 17  Finalist        1361 non-null   float64
 18  Winner          1361 non-null   float64
 19  Acknowledge     683 non-null    float64
 20  Ack Look        683 non-null    float64
 21  Ack Speak       683 non-null    float64
 22  Ack Gesture     683 non-null    float64
 23  Ack Smile       683 non-null    float64
 24  Ack Quote       289 non-null    object
 25  Ack Score       683 non-null    float64
dtypes: bool(1), float64(12), int64(2), object(11)
memory usage: 275.5+ KB

In [44]:
# drop columns from Castaways that aren't needed

df_castaways.drop(columns=['Acknowledge', 'Ack Look', 'Ack Speak', 'Ack Gesture', 'Ack Smile', 'Ack Quote', 'Ack Score'])

,Version,Version Season,Season,Full Name,Castaway Id,Castaway,Age,City,State,Episode,Day,Order,Result,Jury Status,Place,Original Tribe,Jury,Finalist,Winner
0,US,US01,1,Sonja Christopher,US0001,Sonja,63.0,Walnut Creek,California,1.0,3.0,1.0,1st voted out,NaN,16,Tagi,False,0.0,0.0
1,US,US01,1,B.B. Andersen,US0002,B.B.,64.0,Mission Hills,Kansas,2.0,6.0,2.0,2nd voted out,NaN,15,Pagong,False,0.0,0.0
2,US,US01,1,Stacey Stillman,US0003,Stacey,27.0,San Francisco,California,3.0,9.0,3.0,3rd voted out,NaN,14,Tagi,False,0.0,0.0
3,US,US01,1,Ramona Gray,US0004,Ramona,29.0,Edison,New Jersey,4.0,12.0,4.0,4th voted out,NaN,13,Pagong,False,0.0,0.0
4,US,US01,1,Dirk Been,US0005,Dirk,23.0,Spring Green,Wisconsin,5.0,15.0,5.0,5th voted out,NaN,12,Tagi,False,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1398,NZ,NZ02,2,Adam O'Brien,NZ0030,Adam,28.0,Auckland,AUK,13.0,36.0,14.0,13th voted out,6th jury member,5,Khangkhaw,True,0.0,0.0
1399,NZ,NZ02,2,Tara Thorowgood,NZ0031,Tara,44.0,Hamilton,WKO,14.0,38.0,15.0,14th voted out,7th jury member,4,Khangkhaw,True,0.0,0.0
1400,NZ,NZ02,2,Dave Lipanovic,NZ0032,Dave,26.0,Auckland,AUK,15.0,39.0,16.0,2nd runner-up,NaN,3,Chani,False,1.0,0.0
1401,NZ,NZ02,2,Tess Fahey,NZ0033,Tess,24.0,Christchurch,CAN,15.0,39.0,17.0,Runner-up,NaN,2,Khangkhaw,False,1.0,0.0
1402,NZ,NZ02,2,Lisa Stanger,NZ0034,Lisa,38.0,Christchurch,CAN,15.0,39.0,18.0,Sole Survivor,NaN,1,Khangkhaw,False,1.0,1.0

In [45]:
# Take Jury, Finalist, and Winner columns and combine into one column that uses string instead of boolean

## Clean Advantage Details

In [46]:
df_advantage_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Version         395 non-null    object
 1   Version Season  395 non-null    object
 2   Season          395 non-null    int64
 3   Advantage Id    395 non-null    int64
 4   Advantage Type  395 non-null    object
 5   Clue Details    395 non-null    object
 6   Location Found  387 non-null    object
 7   Conditions      194 non-null    object
dtypes: int64(2), object(6)
memory usage: 24.8+ KB

## Clean Advantage Movement

In [56]:
#Advantage Movement info

df_advantage_movement.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 902 entries, 0 to 901
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Version          902 non-null    object
 1   Version Season   902 non-null    object
 2   Season           902 non-null    int64
 3   Castaway         902 non-null    object
 4   Castaway Id      902 non-null    object
 5   Advantage Id     902 non-null    int64
 6   Sequence Id      902 non-null    int64
 7   Day              885 non-null    float64
 8   Episode          885 non-null    float64
 9   Event            902 non-null    object
 10  Played for       274 non-null    object
 11  Played for Id    273 non-null    object
 12  Success          276 non-null    object
 13  Votes Nullified  206 non-null    float64
 14  Sog Id           881 non-null    float64
dtypes: float64(4), int64(3), object(8)
memory usage: 105.8+ KB

In [57]:
#drop columns from Advantage Movement that aren't needed

df_advantage_movement.drop(columns=['Votes Nullified', 'Played for', 'Played for Id', 'Sog Id'])

,Version,Version Season,Season,Castaway,Castaway Id,Advantage Id,Sequence Id,Day,Episode,Event,Success
0,US,US11,11,Gary,US0161,1,1,24.0,9.0,Found,NaN
1,US,US11,11,Gary,US0161,1,2,24.0,9.0,Played,Yes
2,US,US12,12,Terry,US0180,1,1,9.0,4.0,Found,NaN
3,US,US12,12,Terry,US0180,1,2,37.0,15.0,Expired,NaN
4,US,US13,13,Yul,US0202,1,1,5.0,2.0,Found,NaN
...,...,...,...,...,...,...,...,...,...,...,...
897,NZ,NZ02,2,Eve,NZ0028,2,1,7.0,3.0,Found,NaN
898,NZ,NZ02,2,Eve,NZ0028,2,2,15.0,5.0,Played,No
899,NZ,NZ02,2,Josh,NZ0022,3,1,12.0,4.0,Activated,NaN
900,NZ,NZ02,2,Josh,NZ0022,3,2,13.0,5.0,Expired,NaN
901,NZ,NZ02,2,Dave,NZ0032,5,1,19.0,7.0,Found,NaN

In [ ]:
#function to drop non-US rows from a dataframe

#def drop_non_us
    #filtered_df = df[df[]]

In [ ]:
#create SQLite database and connection

In [ ]:
#add data to SQLite

In [ ]:
#SQL Queries

In [ ]:
# Visualization of correlation between number of advantages and place

In [ ]:
# visualization of number of winners with an advantage

In [ ]:
# visualization of number of winners with an advantage played

In [ ]:
#visualization of number of winners with an advantage successfully played